{{- if .Values.metrics.podMonitor.enabled -}}
apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  namespace: {{ default .Release.Namespace .Values.metrics.podMonitor.namespace }}
  labels:
    {{- include "cloudflare-tunnel.labels" . | nindent 4 }}
    {{- with .Values.metrics.podMonitor.additionalLabels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
spec:
  podMetricsEndpoints:
    - port: metrics
      interval: {{ .Values.metrics.podMonitor.scrapeInterval }}
  selector:
    matchLabels:
      {{- include "cloudflare-tunnel.selectorLabels" . | nindent 6 }}
  {{- if .Values.metrics.podMonitor.namespace }}
  namespaceSelector:
    matchNames:
      - {{ .Release.Namespace }}
  {{- end }}
{{- end }}
