# A configmap is used for local tunnel configuration mode.
{{- if eq .Values.cloudflare.tunnelMode "local" }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "cloudflare-tunnel.fullname" . }}
  namespace: {{ .Release.Namespace }}
data:
  config.yaml: |
    # Tunnel name
    tunnel: {{ .Values.cloudflare.tunnelName }}
    # Location of secret containing tunnel credentials
    credentials-file: /etc/cloudflared/creds/credentials.json
    # Support for L3/L4 protocol routing via WARP
    warp-routing:
      enabled: {{ .Values.cloudflare.enableWarp }}
    # Serves metrics server under /metrics and readiness server under /ready
    metrics: 0.0.0.0:2000
    # Autoupdate doesn't apply in Kubernetes as changes are lost when a pod restarts
    no-autoupdate: true
    # Protocol to establish connection between cloudflared and Cloudflare global network
    protocol: {{ .Values.cloudflare.protocol }}
    # Standard loglevel
    loglevel: {{ .Values.cloudflare.logLevel }}
    # Transport protocol loglevel
    transport-loglevel: {{ .Values.cloudflare.transportLogLevel }}
    # Ingress rules, see
    # https://developers.cloudflare.com/cloudflare-one/connections/connect-apps/configuration/ingress
    ingress:
      {{- with .Values.cloudflare.ingress }}
      {{- toYaml . | nindent 6 }}
      {{- end }}
      # catch-all rule responds with HTTP 404
      - service: http_status:404
{{- end }}
